app {
  home = /tmp/wabase-test
  host = "http://127.0.0.1"
}
port = 8080

#auth.crypto.key = 3nkJyrxU9q4tx5nGmH7Ns2DRML9EP6gZF8DvE0DKN2I
#auth.mac.key    = SGXimqa4IGf7dIkOXQSpwhGTBZgWyBoaLErPgpF297w

file-streamer {
  wabase_it_legacy_fs { # put object(s) in your conf to enable filestreamer(s); props are inherited
  }
}

tresql {
  default = wabase_it_legacy_cp
}

jdbc.cp {
  wabase_it_legacy_cp {
    poolName = wabase_it_legacy_cp
    jdbcUrl  = "jdbc:hsqldb:mem:mymemdb"
    username = "SA"
    password = ""
    autoCommit = false
    maximumPoolSize = 2
  }
}
