app {
  home = /tmp/wabase-test
  host = "http://127.0.0.1"
  public-views.location-pattern = "(?!(roles-test)).*\\.yaml"  # path/and/filename pattern to allow access to view api without user and role check
  deferred-requests.requests = [slow-respond]
  wabase-call-alias {
    audit = wabase.app.Audit.handleAuditing
    sleep = wabase.app.BusinessScenariosSpecs.sleep
  }
  script-validations {
    enabled = true
    init = org.wabase.WabaseScriptValidation.initWabaseScriptValidation
    script-engine-factory = org.wabase.WabaseScriptValidation.scriptEngineFactory
    script-engine-init = org.wabase.WabaseScriptValidation.initScriptEngine
    custom-functions-init = org.wabase.WabaseScriptValidation.customFunctions
    load-validations = wabase.app.ScriptValidations.loadValidations
  }
  job {
    scheduler-initializer = org.wabase.scheduler.QuartzScheduler.init
    job-status-cp = "wabase_it_cp"
    clean-jobs-on-start = false
    max-time = "1 hour"
  }
  marshal_key_as_json = false   #TODO refactor tests and remove this line
}
port = 8080

auth.crypto.key = 3nkJyrxU9q4tx5nGmH7Ns2DRML9EP6gZF8DvE0DKN2I
auth.mac.key    = SGXimqa4IGf7dIkOXQSpwhGTBZgWyBoaLErPgpF297w

tresql {
  default = wabase_it_cp
}

jdbc.cp {
  wabase_it_cp {
    poolName = wabase_it_cp
    jdbcUrl  = "jdbc:hsqldb:mem:mymemdb"
    username = "SA"
    password = ""
    autoCommit = false
    maximumPoolSize = 2
  }
  wabase_it_audit_cp {
    poolName = wabase_it_audit_cp
    jdbcUrl  = "jdbc:hsqldb:mem:mymemdb"
    username = "SA"
    password = ""
    autoCommit = false
    maximumPoolSize = 1
  }
}
