name: Build and test
on:   [push]
jobs:
  Build-and-test:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os:   [ubuntu-latest]  # TODO macos-latest, windows-latest
        java: [8, 11]          # TODO java 17
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Compile and test and check version policy
      run:  sbt clean update +compile +test +it:test +versionPolicyCheck
